services:
  - type: web
    name: demanda-cpfl
    runtime: python
    region: ohio
    plan: free
    rootDir: Web_app_render
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:${PORT:-5000} --workers 2 --timeout 120

databases:
  - name: demanda-cpfl-db
    databaseName: projetos
    plan: free
    region: ohio
